### ISSUE TITLE
Add pasteConfig which includes <hr>

### ISSUE THREAD

**Issue by benlammers** [editor-js/delimiter#27]
Current behaviour: Does not recognize pasted `<hr>` as Delimiter blocks

Desired behaviour: Pasted `<hr>` elements become Delimiter blocks

Looks like would be a simple change to add `pasteConfig` and a simple onPaste() method

**Comment by Sozialarchiv** [comment]
This ticket is fixed.

**Comment by neSpecc** [comment]
Resolved by #36
